/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package orders;

import org.junit.jupiter.api.Test;
//import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        //Client classUnderTest = new Client();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
